# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    my.oauth_aware.user_provider.service:
        class: AppBundle\Security\FOSUBUserProvider
        arguments:
            - '@fos_user.user_manager'
            - {facebook: facebookId, vkontakte: vkontakteId}
    app.form.profile:
        class: AppBundle\Form\ProfileType
        tags:
            - { name: form.type, alias: app_user_profile }
